AWSTemplateFormatVersion: '2010-09-09'
Transform: ["AWS::Serverless-2016-10-31"]
Description: >
  customer-coding-evaluation-app
    
Globals:
  Function:
    Runtime: nodejs14.x
    Timeout: 60
    MemorySize: 128
    Environment:
      Variables:
        CustomersTable: !Ref CustomersTable
        NODE_OPTIONS: "--enable-source-maps"
  Api:
    Cors:
      AllowOrigin: "'*'" 
      AllowHeaders: "'Content-Type,Authorization'" 


Parameters:
  Environment:
    Type: String

Resources:

  # API definition

  ## HTTP protocol

  HttpApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Sub ${Environment}
  
  MyHttpApiGatewayResponse:
    Type: "AWS::ApiGateway::GatewayResponse"
    Properties:
      ResponseParameters:
        "gatewayresponse.header.Access-Control-Allow-Origin": "'*'"
        "gatewayresponse.header.Access-Control-Allow-Headers": "'*'"
      ResponseType: UNAUTHORIZED
      RestApiId: !Ref HttpApiGateway
      StatusCode: "401"


  # Protected API endpoints
  CustomersEndpointsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub ${Environment}
      CodeUri: dist/customers
      Handler: index.default
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Events:
        ListCustomersEndpoint:
          Type: Api
          Properties:
            Path: /customers
            Method: get
            RestApiId: !Ref HttpApiGateway

        GetCustomerEndpoint:
          Type: Api
          Properties:
            Path: /customers/{customerId}
            Method: get
            RestApiId: !Ref HttpApiGateway

        EditCustomerEndpoint:
          Type: Api
          Properties:
            Path: /customers/{customerId}
            Method: put
            RestApiId: !Ref HttpApiGateway

        DeleteCustomerEndpoint:
          Type: Api
          Properties:
            Path: /customers/{customerId}
            Method: delete
            RestApiId: !Ref HttpApiGateway


  # Tables
  CustomersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        - AttributeName: customerId
          AttributeType: S
      KeySchema: 
        - AttributeName: customerId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST 


Outputs:
  ApiURL:
    Description: API Gateway endpoint URL for back app
    Value:
      Fn::Sub: https://${HttpApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/